### PR TITLE
Update quarkus-l10n-utils to 0.5.3

### PR DESCRIPTION
**Pull request by ynojima**
to address quarkusio.github.io repository default branch name change
Ref. https://github.com/quarkusio/quarkusio.github.io/issues/1952

### CODE REVIEW

**Comment by yrodiere** [comment]
@maxandersen @gsmet @gastaldi we might need your help to get this through? It's blocking sync for the Spanish website.

**Review by gsmet — APPROVED** [review]

**Comment by ynojima** [comment]
@gsmet Thank you for merging this pull-request. 
May I also ask you to invoke `sync-upstream` GitHub Actions workflow(https://github.com/quarkusio/es.quarkus.io/actions/workflows/sync.yml) ? It will resolve this issue: https://github.com/quarkusio/search.quarkus.io/issues/130#issuecomment-2132737612

**Comment by maxandersen** [comment]
afaics sync.yml ran 3 days ago - is that sufficient @ynojima ?

**Comment by ynojima** [comment]
Yes, as far as I know, no issue is left regarding default branch name change.

**Pull request merged**
